# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.3.0'

gem 'faraday', '~> 2.9'
gem 'tty-prompt', '~> 0.23'
gem 'tty-box', '~> 0.7'
gem 'tty-cursor', '~> 0.7'
gem 'tty-screen', '~> 0.8'
gem 'tty-spinner', '~> 0.9'
gem 'pastel', '~> 0.8'
